### ISSUE TITLE
Specifying path to check

### ISSUE THREAD

**Issue by smalbadger** [RojerGS/python-black-check#4]
Are there any special tricks needed to specify the path? I'm assuming that this action runs in the root directory of the repo. When I specify `path: '.'`, no python files are detected and when I specify `path: './pymessagelib'`, it says the directory doesn't exist.

To see my folder structure, visit my repo here: https://github.com/smalbadger/pymessagelib

Thanks in advance for the help.

**Comment by rodrigogiraoserrao** [comment]
Hey there, thanks for opening up this issue.

I see your `main.yml` file has the comment line
`# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it`
but you are missing the action that actually checks out the repository, to make it accessible; something like
`    - uses: actions/checkout@v2`.

See, for e.g., the `main.yaml` file I have here: [https://github.com/RojerGS/chatbot-provis/blob/master/.github/workflows/main.yml](https://github.com/RojerGS/chatbot-provis/blob/master/.github/workflows/main.yml).

**Comment by smalbadger** [comment]
@RojerGS thanks for the help! I appreciate the work you've put in to make this action. That resolved it for me.

Cheers!
